spring:
  datasource:
    url: jdbc:mysql://${db.url}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}
      database: ${redis.database}

# jwt 토큰 사용을 위한 비밀키
jwt:
  secret:
    key: ${jwt.key}



data:
  redis:
    password: ${redis.password}
    host: ${redis.host}
    port: ${redis.port}
